<a href="https://colab.research.google.com/github/MythilyCrazy/numpy1/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#numpy supports conceptual array

In [ ]:
#scalar dimension array
arr1 = np.array(5)
arr1.ndim

0

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
#one dimension array
arr2 = np.array([1,2,3])
arr2.ndim

1

In [ ]:
#two dimension array
arr3 = np.array([[1,2,3],[4,5,6]],dtype=float)
arr3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr3.ndim

2

In [ ]:
#three dimension array
arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr4


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#dimension
arr4.ndim

3

In [ ]:
#defining no.of.dimensions or converting one dim into another dim
import numpy as np
b1 = np.array([1,2,3,4],ndmin=6)
b1

array([[[[[[1, 2, 3, 4]]]]]])

In [ ]:
#creating array of zeroes
z = np.zeros((2,3),dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#creating array of ones
o = np.ones((3,3),dtype=int)
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#creating identity matrix in which diagnols are 1.
i = np.eye((3),dtype=int)
i

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
i = np.eye(3,5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
i = np.eye(4,k=-1)
i

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
i = np.eye(4,k=2)
i

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
i = np.eye((5),dtype=int)
i

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
a = np.arange(2,2000,500)
a

array([   2,  502, 1002, 1502])

In [ ]:
#Accessing array elements
a=np.array([10,20,30,40])
print(a[0])
print(a[1])
print(a[2])
print(a[2]+a[3])

10
20
30
70


In [ ]:
#Access 2d array
a = np.array([[1,2,3],[4,5,6]])
print(a[1,1])

5


In [ ]:
#Access 3d array
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a[0,1,2])
print(a[0,0,2])
print(a[1,0,0])
print(a[1,1,2])

6
3
7
12


In [ ]:
#access negative indexing
a = np.array([[1,2,3,5,6],[4,5,6,7,8]])
print(a[0,4])
print(a[0,-3])
print(a[1,2])
print(a[1,-5])

6
3
6
4


In [ ]:
#slicing array
import numpy as np

a = np.array([10,30,50,70,90,100])
print(a[-1])
print(a[0:3])
print(a[-3])
print(a[::3])

100
[10 30 50]
70
[10 70]


In [ ]:
import numpy as np
a = np.array([[15,12,78,32],[89,76,52,31]])
print(a[0,0:4])
print(a[1,2])
print(a[0:2,2])
print(a[0:2,1:3])

[15 12 78 32]
52
[78 52]
[[12 78]
 [76 52]]


In [ ]:
#datatype
a = np.array([1,2,3,4])
print(a.dtype)

int64


In [ ]:
a = np.array([1,2,3,4],dtype = 'S')
print(a.dtype)

|S1


In [ ]:
a = np.array([1.2,2.1,0])
b = a.astype(int)
print(b)
print(b.dtype)
c = b.astype(bool)
print(c)
print(c.dtype)

[1 2 0]
int64
[ True  True False]
bool


In [ ]:
a = np.array([10,20,30,40,50])
b = a.copy()
a[2]=90
print(a)
print(b)


[10 20 90 40 50]
[10 20 30 40 50]


In [ ]:
a = np.array([10,20,30,40,50])
b = a.view()
a[2]=90
print(a)
print(b)

[10 20 90 40 50]
[10 20 90 40 50]
